import dotenv from 'dotenv';
dotenv.config();

const { 
  PORT, 
  NODE_ENV, 
  MONGO_URI,
  QOREID_CLIENT_KEY,
  QOREID_SECRET_KEY,
  JWT_SECRET_KEY,
  SENDGRID_API_KEY,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_USER,
  EMAIL_PASS,
  EMAIL_FROM,
  ONESIGNAL_APP_ID,
  ONESIGNAL_REST_KEY
} = process.env;

export { 
  PORT, 
  NODE_ENV, 
  MONGO_URI,
  QOREID_CLIENT_KEY,
  QOREID_SECRET_KEY,
  JWT_SECRET_KEY,
  SENDGRID_API_KEY,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_USER,
  EMAIL_PASS,
  EMAIL_FROM,
  ONESIGNAL_APP_ID,
  ONESIGNAL_REST_KEY
};
