import dotenv from 'dotenv';
dotenv.config();

const { 
  PORT, 
  NODE_ENV, 
  MONGO_URI,
  DIDIT_WEBHOOK_SECRET,
  JWT_SECRET_KEY,
  ONESIGNAL_APP_ID,
  ONESIGNAL_REST_KEY,
  PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY,
  PAYSTACK_CALLBACK_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  QOREID_CLIENT_ID,
  QOREID_SECRET_KEY,
  GOOGLE_CLIENT_ID
} = process.env;

export { 
  PORT, 
  NODE_ENV, 
  MONGO_URI,
  DIDIT_WEBHOOK_SECRET,
  JWT_SECRET_KEY,
  ONESIGNAL_APP_ID,
  ONESIGNAL_REST_KEY,
  PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY,
  PAYSTACK_CALLBACK_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  QOREID_CLIENT_ID,
  QOREID_SECRET_KEY,
  GOOGLE_CLIENT_ID
};